name: skuu_web
description: skuuweb

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.4
  flutter_screenutil: ^5.5.4
  dash_chat_2: ^0.0.15
#  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.3
  auto_size_text: ^3.0.0
  adaptive_dialog: ^1.8.0+1
  flutter_staggered_grid_view: ^0.6.2
  dash_chat: ^1.1.16
  image_network: ^2.5.1
  url_launcher: ^6.1.8
  flukit: ^3.0.1
  lpinyin: ^2.0.3
  scrollable_positioned_list: ^0.3.5


dev_dependencies:
  flutter_webrtc: ^0.9.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
#  fonts:
    #设置字体后，反而变慢了
#    - family: Noto
#      fonts:
#        - asset: fonts/NotoSansSC-Bold.otf
#        - asset: fonts/NotoSansSC-Medium.otf
#        - asset: fonts/NotoSansSC-Regular.otf
#          style: normal
  assets:
    - mock/
    - imgs/
    - imgs/index1.png
    - imgs/index1_select.png
    - imgs/msg.png
    - imgs/msg_select.png
    - imgs/video_select.png
    - imgs/video.png
    - imgs/find_select.png
    - imgs/find.png
    - imgs/me.png
    - imgs/me_select.png
    - imgs/img_default.png
    - imgs/discuss.png
    - imgs/team.png
    - imgs/room.png
    - imgs/user_default.png
    - imgs/care.png
    - imgs/history.png
    - imgs/collect.png
    - imgs/order.png
    - imgs/fuli.png
    - imgs/shop.png
    - imgs/fankui.png
    - imgs/set.png
    - imgs/sun.png
    - imgs/night.png
    - imgs/version.png
    - imgs/exit.png
    - imgs/level.png
    - imgs/level-1.png
    - imgs/level-2.png
    - imgs/idea.png
    - imgs/artical.png
    - imgs/put_video.png
    - imgs/answer.png
    - imgs/send_friend.png
    - imgs/link.png
    - imgs/qq.png
    - imgs/wechat.png
    - imgs/defbak.png
    - imgs/defbak1.png
